//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenMenu.Web.Client.Resources {

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenMenu.Web.Client.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }

        internal static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }

        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }

        internal static string AddTo {
            get {
                return ResourceManager.GetString("AddTo", resourceCulture);
            }
        }

        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }

        internal static string BackToCategories {
            get {
                return ResourceManager.GetString("BackToCategories", resourceCulture);
            }
        }

        internal static string BackToMenu {
            get {
                return ResourceManager.GetString("BackToMenu", resourceCulture);
            }
        }

        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }

        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        internal static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }

        internal static string CategoryRequired {
            get {
                return ResourceManager.GetString("CategoryRequired", resourceCulture);
            }
        }

        internal static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }

        internal static string ConfirmDeleteCategory {
            get {
                return ResourceManager.GetString("ConfirmDeleteCategory", resourceCulture);
            }
        }

        internal static string ConfirmDeleteItem {
            get {
                return ResourceManager.GetString("ConfirmDeleteItem", resourceCulture);
            }
        }

        internal static string CreateOneFirst {
            get {
                return ResourceManager.GetString("CreateOneFirst", resourceCulture);
            }
        }

        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }

        internal static string CurrencyHint {
            get {
                return ResourceManager.GetString("CurrencyHint", resourceCulture);
            }
        }

        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }

        internal static string DashboardAdminHint {
            get {
                return ResourceManager.GetString("DashboardAdminHint", resourceCulture);
            }
        }

        internal static string DashboardMenuHint {
            get {
                return ResourceManager.GetString("DashboardMenuHint", resourceCulture);
            }
        }

        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }

        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }

        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }

        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }

        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }

        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }

        internal static string FieldTooLong {
            get {
                return ResourceManager.GetString("FieldTooLong", resourceCulture);
            }
        }

        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }

        internal static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }

        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }

        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }

        internal static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }

        internal static string LoginHeading {
            get {
                return ResourceManager.GetString("LoginHeading", resourceCulture);
            }
        }

        internal static string LogoUrl {
            get {
                return ResourceManager.GetString("LogoUrl", resourceCulture);
            }
        }

        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }

        internal static string MenuItems {
            get {
                return ResourceManager.GetString("MenuItems", resourceCulture);
            }
        }

        internal static string MenuItemsStat {
            get {
                return ResourceManager.GetString("MenuItemsStat", resourceCulture);
            }
        }

        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        internal static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }

        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }

        internal static string NoCategories {
            get {
                return ResourceManager.GetString("NoCategories", resourceCulture);
            }
        }

        internal static string NoCategoriesAvailable {
            get {
                return ResourceManager.GetString("NoCategoriesAvailable", resourceCulture);
            }
        }

        internal static string NoCategoriesForItems {
            get {
                return ResourceManager.GetString("NoCategoriesForItems", resourceCulture);
            }
        }

        internal static string NoItemsInCategory {
            get {
                return ResourceManager.GetString("NoItemsInCategory", resourceCulture);
            }
        }

        internal static string NoSettingsWarning {
            get {
                return ResourceManager.GetString("NoSettingsWarning", resourceCulture);
            }
        }

        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }

        internal static string OrderRange {
            get {
                return ResourceManager.GetString("OrderRange", resourceCulture);
            }
        }

        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        internal static string PoweredByOpenMenu {
            get {
                return ResourceManager.GetString("PoweredByOpenMenu", resourceCulture);
            }
        }

        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }

        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }

        internal static string PriceRange {
            get {
                return ResourceManager.GetString("PriceRange", resourceCulture);
            }
        }

        internal static string RestaurantSettings {
            get {
                return ResourceManager.GetString("RestaurantSettings", resourceCulture);
            }
        }

        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        internal static string SettingsDescription {
            get {
                return ResourceManager.GetString("SettingsDescription", resourceCulture);
            }
        }

        internal static string SettingsHint {
            get {
                return ResourceManager.GetString("SettingsHint", resourceCulture);
            }
        }

        internal static string SettingsName {
            get {
                return ResourceManager.GetString("SettingsName", resourceCulture);
            }
        }

        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }

        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }

        internal static string SoldOut {
            get {
                return ResourceManager.GetString("SoldOut", resourceCulture);
            }
        }

        internal static string StaffLogin {
            get {
                return ResourceManager.GetString("StaffLogin", resourceCulture);
            }
        }

        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        internal static string UnauthorizedUsersNote {
            get {
                return ResourceManager.GetString("UnauthorizedUsersNote", resourceCulture);
            }
        }

        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }

        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }

        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }

        internal static string VisibleOnPublicMenu {
            get {
                return ResourceManager.GetString("VisibleOnPublicMenu", resourceCulture);
            }
        }

        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
